export type SeekResult = { ok: true; seconds: number } | { ok: false; reason: "media-unavailable" | "seek-failed" | "invalid-time" | "timeout"; message: string };
export type SeekTarget = { seconds: number };
export async function seekVideo(element: HTMLVideoElement | null, target: SeekTarget, timeoutMs = 1500): Promise<SeekResult> {
  if (!Number.isFinite(target.seconds) || target.seconds < 0 || target.seconds > 86400) return { ok: false, reason: "invalid-time", message: "Choose a timestamp between 0 and 86400 seconds." };
  if (!element || element.readyState < HTMLMediaElement.HAVE_METADATA || !Number.isFinite(element.duration) || element.duration <= target.seconds) return { ok: false, reason: "media-unavailable", message: "Video media is unavailable or shorter than this timestamp; seek was not performed." };
  const seekable = Array.from({ length: element.seekable.length }, (_, i) => [element.seekable.start(i), element.seekable.end(i)] as const).some(([start, end]) => target.seconds >= start && target.seconds <= end);
  if (!seekable) return { ok: false, reason: "seek-failed", message: "This timestamp is not seekable in the loaded media." };
  return new Promise((resolve) => { let done = false; const finish = (result: SeekResult) => { if (done) return; done = true; clearTimeout(timer); element.removeEventListener("seeked", onSeeked); element.removeEventListener("error", onError); resolve(result); }; const onSeeked = () => finish(Math.abs(element.currentTime - target.seconds) < 0.25 ? { ok: true, seconds: target.seconds } : { ok: false, reason: "seek-failed", message: "The browser did not reach the requested timestamp." }); const onError = () => finish({ ok: false, reason: "seek-failed", message: "The browser could not seek this media." }); const timer = setTimeout(() => finish({ ok: false, reason: "timeout", message: "The browser did not confirm the seek in time." }), timeoutMs); element.addEventListener("seeked", onSeeked, { once: true }); element.addEventListener("error", onError, { once: true }); try { element.currentTime = target.seconds; } catch { finish({ ok: false, reason: "seek-failed", message: "The browser could not seek this media." }); } });
}
